WIDTH, HEIGHT = 800, 600
PLAYFIELD_HEIGHT = 500
PLAYFIELD_WIDTH = PLAYFIELD_HEIGHT / 2
PLAYFIELD_X = 300
PLAYFIELD_Y = (HEIGHT - PLAYFIELD_HEIGHT) / 2
PLAYFIELD_HORIZONTAL_END = PLAYFIELD_X + PLAYFIELD_WIDTH
CAPTION = "Pytris"
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
FIELDS_BACKGROUND = (31, 33, 64)
BACKGROUND = (10, 11, 23)
FPS = 60
DAS_MAX = FPS // 4
COLS = 10
ROWS = 20
NEXT_FIELD_COLS = 5
NEXT_FIELD_ROWS = 10
ON_HOLD_COLS = 6
ON_HOLD_ROWS = 4
INITIAL_SCORE = 0
INITIAL_LEVEL = 1
INITIAL_LINES = 0
INITIAL_PAUSE = False
INITIAL_TICKER = 0
INITIAL_LOCK_COUNTER = 0
INITIAL_ON_HOLD = None
INITIAL_CAN_HOLD = True
INITIAL_IS_DROPPING = False

GAME_BASE_VELOCITY = 1
GRAVITY = 60
INITIAL_DELAY = 1100

DEFAULT_AVAILABLE_ROW = 18
DEFAULT_MAX_AVAILABLE_ROW = 20

ROTATION_TESTS_ATTEMPTS = 5

BASE_SQUARE_SIZE = int(PLAYFIELD_HEIGHT / 20)
MAX_TETROMINO_HEIGHT = BASE_SQUARE_SIZE*2
FIGURES_SIZES = {
    1: (BASE_SQUARE_SIZE*4, BASE_SQUARE_SIZE),
    2: (BASE_SQUARE_SIZE*3, MAX_TETROMINO_HEIGHT),
    3: (BASE_SQUARE_SIZE*3, MAX_TETROMINO_HEIGHT),
    4: (BASE_SQUARE_SIZE*3, MAX_TETROMINO_HEIGHT),
    5: (BASE_SQUARE_SIZE*3, MAX_TETROMINO_HEIGHT),
    6: (BASE_SQUARE_SIZE*3, MAX_TETROMINO_HEIGHT),
    7: (BASE_SQUARE_SIZE*2, MAX_TETROMINO_HEIGHT),
}

BASE_NEXT_FIELD_PADDING = int(BASE_SQUARE_SIZE / 2)
NEXT_FIELD_MARGIN_START = BASE_SQUARE_SIZE * 2
NEXT_FIELD_X = PLAYFIELD_HORIZONTAL_END + NEXT_FIELD_MARGIN_START
NEXT_FIELD_MARGIN_TOP = BASE_SQUARE_SIZE
NEXT_FIELD_Y = PLAYFIELD_Y + NEXT_FIELD_MARGIN_TOP * 2
NEXT_FIELD_WIDTH = BASE_SQUARE_SIZE * 5
NEXT_FIELD_HEIGHT = BASE_SQUARE_SIZE * 6 + BASE_NEXT_FIELD_PADDING * 4


BASE_HOLD_FIELD_PADDING = int(BASE_SQUARE_SIZE / 2)
HOLD_FIELD_MARGIN_END = BASE_SQUARE_SIZE * 2
HOLD_FIELD_WIDTH = BASE_SQUARE_SIZE * 5
HOLD_FIELD_HEIGHT = BASE_SQUARE_SIZE * 2 + BASE_HOLD_FIELD_PADDING * 2
HOLD_FIELD_X = PLAYFIELD_X - HOLD_FIELD_WIDTH - HOLD_FIELD_MARGIN_END
HOLD_FIELD_MARGIN_TOP = BASE_SQUARE_SIZE
HOLD_FIELD_Y = PLAYFIELD_Y + HOLD_FIELD_MARGIN_TOP * 2
