WIDTH, HEIGHT = 800, 600
PLAYFIELD_HEIGHT = 500
PLAYFIELD_WIDTH = PLAYFIELD_HEIGHT / 2
PLAYFIELD_X = 300
PLAYFIELD_Y = (HEIGHT - PLAYFIELD_HEIGHT) / 2
CAPTION = "Pytris"
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
PLAYFIELD_BACKGROUND = (31, 33, 64)
BACKGROUND = (10, 11, 23)
FPS = 60
COLS = 10
ROWS = 20
PREVIEW_COLS = 6
PREVIEW_ROWS = 10
ON_HOLD_COLS = 6
ON_HOLD_ROWS = 4

GAME_BASE_VELOCITY = 1
GRAVITY = 60
INITIAL_DELAY = 1100

DEFAULT_AVAILABLE_ROW = 18
DEFAULT_MAX_AVAILABLE_ROW = 20

ROTATION_TESTS_ATTEMPTS = 5

BASE_SQUARE_SIZE = PLAYFIELD_HEIGHT / 20
FIGURES_SIZES = {
    1: (BASE_SQUARE_SIZE*4, BASE_SQUARE_SIZE),
    2: (BASE_SQUARE_SIZE*3, BASE_SQUARE_SIZE*2),
    3: (BASE_SQUARE_SIZE*3, BASE_SQUARE_SIZE*2),
    4: (BASE_SQUARE_SIZE*3, BASE_SQUARE_SIZE*2),
    5: (BASE_SQUARE_SIZE*3, BASE_SQUARE_SIZE*2),
    6: (BASE_SQUARE_SIZE*3, BASE_SQUARE_SIZE*2),
    7: (BASE_SQUARE_SIZE*2, BASE_SQUARE_SIZE*2),
}
